config/routes.rb
MetastudioNews::Application.routes.draw do
  resources :votes
  resources :news
  devise_for :users

  resources :users do
    resources :news
  end

  root :to => 'news#index'

end

app/models/news.rb
# == Schema Information
#
# Table name: news
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  body       :text             not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class News < ActiveRecord::Base
  attr_accessible :body, :title, :user_id
  belongs_to :user

  has_many :votes

  validates_presence_of  :body
  validates :title, presence: true, length: { maximum: 150 }

  def voted_on?(user)
    0 < Vote.where(
        :new_id => self.id,
        :user_id => user.id,
    ).count
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :news
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :news_id, :user_id

  belongs_to :news, :counter_cache => true
  belongs_to :user

  validates_uniqueness_of :news_id, scope: [:user_id]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  respond_to :html

  def index
    params[:user_id].blank? ? @news = News.order('created_at, votes_count DESC').page(params[:page]) : @news = News.where(user_id: params[:user_id]).order('created_at,votes_count DESC').page(params[:page])
    respond_with @news
  end

  def show
    @vote = Vote.new(params[:vote])

    begin
      @news = News.find(params[:id])
    rescue
      flash[:error] = 'Invalid news.'
      redirect_to root_url
    else
      respond_with @news
    end
  end

  def new
    respond_with @news = News.new
  end

  def create
    @news = News.new(params[:news])
    respond_with(@news) do |format|
      if @news.save
        flash[:success] = 'News was successefully created.'
        format.html { redirect_to @news }
      else
        format.html { render :action => :new }
      end
    end
  end

  def edit
    respond_with @news = News.find(params[:id])
  end

  def update
    @news = News.find(params[:id])
    respond_with(@news) do |format|
      if @news.update_attributes(params[:news])
        flash[:success] = 'News was successefully updated.'
        format.html { redirect_to @news }
      else
        format.html { render :action => :edit }
      end
    end
  end

  def destroy
    @news = News.find(params[:id])
    @news.destroy
    flash[:success] = 'News was successefully destroyed.'
    redirect_to root_url
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :authenticate_user!

  respond_to :html

  def new
    @vote = Vote.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @vote }
    end
  end

  def create
    @vote = Vote.new(params[:vote])
    nid = params[:vote][:news_id].to_i
    uid = params[:vote][:user_id].to_i
    @count = Vote.where(news_id: nid, user_id: uid).count

    if @count == 0
      respond_to do |format|
        if @vote.save
          #flash[:success] = 'You have successfully voted.'
          format.js
          format.html { redirect_to news_path }
        else
          #flash[:error] = 'You can vote only once.'
          format.html { redirect_to news_path }
          format.xml  { render :xml => @vote.errors, :status => :unprocessable_entity }
        end
      end
    else
      render js: "alert('You may vote once for any one news.');"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
  def get_user_email_by_id(id)
    User.find(id).email
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Maxim Zhukov © 2013
  </small>
</footer>

app/views/layouts/_header.html.erb
<ul class="nav nav-pills pull-right">
  <% if user_signed_in? %>
    <li><%= link_to current_user.email, edit_user_registration_path %></li>
    <li class="dropdown">
      <a class="dropdown-toggle" id="drop4" role="button" data-toggle="dropdown" href="#">Manage News <b class="caret"></b></a>
      <ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="drop4">
        <li role="presentation">
          <%= link_to 'All my news', user_news_index_path(current_user), html_options = {role: 'menuitem', tabindex: '-1'} %>
        </li>
        <li role="presentation">
          <%= link_to 'Add News', new_news_path, html_options = {role: 'menuitem', tabindex: '-1'} %>
        </li>
      </ul>
    </li>
    <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
  <% else %>
    <li><%= link_to 'Sign in', new_user_session_path %></li>
    <li><%= link_to 'Sign up', new_user_registration_path %></li>
  <% end %>
</ul>

app/views/layouts/_notice.html.erb
<% flash.each do |key, value| %>
  <%= content_tag :div, class: "alert alert-#{key} fade in" do %>
    <%= content_tag :button, :class => 'close', :'data-dismiss' => 'alert' do %>
       &#215;
    <% end %>
    <%= value %>
  <% end %>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src='http://html5shim.googlecode.com/svn/trunk/html5.js'></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <title>MetastudioNews</title>
    <%= stylesheet_link_tag    'application', :media => 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div class="container-narrow">
      <div class="masthead">
        <%= render 'layouts/header' %>
        <h3 class="muted"><%= link_to 'MetastudioNews', root_path %></h3>
        <h5 class="muted">Тестовое задание на вакансию Ruby on Rails разработчик в компанию MetaStudio</h5>
      </div>
      <hr/>
      <!--Body content-->
      <div class="row">
        <%= render 'layouts/notice' %>
        <%= yield %>
      </div>
      <!--Footer content-->
      <%= render 'layouts/footer' %>
    </div>
    <%#= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/news/_form.html.erb
<%= simple_form_for(@news, :html => { :class => 'form-horizontal' }) do |f| %>

  <% if notification = f.error_notification %>
    <div class="alert alert-error fade in">
      <a class="close" data-dismiss="alert" href="#">&times;</a>
      <%= notification %>
    </div>
  <% end %>

  <%= f.input :title %>
  <%= f.input :user_id %>
  <%= f.input :body %>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
  </div>
<% end %>

app/views/news/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', news_path(@news) %> |
<%= link_to 'Back', :back %>

app/views/news/index.html.erb
<% unless @news.empty? %>
  <%= paginate @news, :window => 2 %>

  <% @news.each do |news| %>
    <div class="span9">
      <blockquote>
        <p><%= news.title %></p>
        <small><%= "#{news.created_at.strftime('%B %e, %Y')} by #{get_user_email_by_id(news.user_id)}" %></small>
      </blockquote>
      <p><%= truncate(news.body, :length => 250, :separator => ' ') %></p>
      <p><%= link_to 'View details »', news_path(news) %></p>
    </div>
  <% end %>

  <%= paginate @news, :window => 2 %>
<% else %>
  <h3>No news</h3>
<% end %>

app/views/news/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/news/show.html.erb
<div class="row">
  <% if user_signed_in? && @news.user_id == current_user.id %>
    <div class="span10" style="text-align: right;">
      <div class="btn-group" style="margin: 9px 0;">
        <%= link_to 'Edit', edit_news_path(@news), :class => 'btn btn-primary' %>
        <%= link_to 'Destroy', @news, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
      </div>
    </div>
  <% end %>
  <legend><%= @news.title %></legend>
  <div class="span9">
    <p><%= @news.body %></p>
    <p class="text-right"><small><%= "#{@news.created_at.strftime('%B %e, %Y')}, by #{get_user_email_by_id(@news.user_id)}" %></small></p>
  </div>
  <% if user_signed_in? %>
    <%= form_for(@vote, :remote => true) do |f| %>
      <%= f.hidden_field 'news_id', :value => @news.id %>
      <%= f.hidden_field 'user_id', :value => current_user.id %>
      <%= f.submit %>
    <% end %>
  <% end %>
</div>

app/views/votes/create.js.erb
$(document).ready(function(){

  alert('You have successfully voted.');

});